
import "./globals.css";
import AuthProvider from "../../Component/Provider/Provider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by Create Next App",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
      
        <AuthProvider>
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}
