/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 spiderman.glb 
*/
"use client"
import React,{useEffect, useState} from 'react'
import { useGraph,useFrame } from '@react-three/fiber'
import { useGLTF, useAnimations} from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default  function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/spiderman.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
 
  const [currentAction, setCurrentAction]=useState("move1");
  const [position, setPosition]=useState([0, -1, -2]);
  useEffect(() => {
    if (actions) {
      actions[currentAction]?.reset().fadeIn(0.5).play();
    }

    return () => {
      actions[currentAction]?.fadeOut(0.5).stop();
    };
  }, [currentAction, actions]);

  useEffect(() => {
    const timeout = setTimeout(() => {
      setCurrentAction("listeningmusic");
      setPosition([0,-1,3])
    }, 1800);

    return () => clearTimeout(timeout);
  }, []);



  return (
    <group ref={group} {...props} dispose={null} position={position} rotation={[0.2,0,0]}>
      <group name="Scene">
        <group name="Sketchfab_model" position={[0.041, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Armature_66" rotation={[Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Spider-Man_65" position={[0.041, 0, 0]} />
        <group name="Armature002" position={[0.041, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Object_10001" geometry={nodes.Object_10001.geometry} material={materials['White.002']} skeleton={nodes.Object_10001.skeleton} />
          <skinnedMesh name="Object_7001" geometry={nodes.Object_7001.geometry} material={materials['material.002']} skeleton={nodes.Object_7001.skeleton} />
          <skinnedMesh name="Object_8001" geometry={nodes.Object_8001.geometry} material={materials['Blue.002']} skeleton={nodes.Object_8001.skeleton} />
          <skinnedMesh name="Object_9001" geometry={nodes.Object_9001.geometry} material={materials['Black.002']} skeleton={nodes.Object_9001.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/spiderman.glb')
